### ISSUE TITLE
what if zookeeper is down?

### ISSUE THREAD

**Issue by yswu** [disqus/menagerie#1]
what happens when zookeeper cluster is not available? can you still launch the site? @davedash

**Comment by tkaemming** [comment]
Since the settings that are stored in ZooKeeper can influence the behavior of your application at startup, I felt that the safest behavior in this case is to allow the exception (socket timeout, connection refused, etc.) to propagate from `menagerie.configure`. This could cause a worker to die on start if it cannot connect.

If the default Kazoo connection timeout (currently 10 seconds) is too high or low for your tastes, you can change it by partially applying that argument, like so:

```
import functools, menagerie
from kazoo.client import KazooClient

menagerie.configure(client=functools.partial(KazooClient, timeout=5))
```

You can also use the settings holder directly if you want to change the start up behavior more significantly. `menagerie.configure` was designed primarily for convenience, since I anticpated this being the generally desired behavior -- better to have a worker crash out on startup then have a lot of workers running configured differently than you had expected.

The holder itself should be resilient to network partitions — e.g. if you're already connected, getting partitioned from ZooKeeper should not cause any errors, although you will miss settings any updates until you've been reconnected to the cluster. I've considered adding some sort of "timeout" after which to purge all custom settings from ZooKeeper, falling back to your application defaults/global defaults, but haven't done so just for the sake of simplicity right now.

**Comment by yswu** [comment]
Thanks a lot for quick reply. I just wanted to confirm with you about the current behavior. I totally understand the simplicity argument.
